### ISSUE TITLE
IoT Adapter Konfiguration verschwindet - Adapter nicht mehr nutzbar

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.iot#85]
Hi,
wenn ich die Konfig des IoT Adapters öffne sehe ich alle Tabs der Konfig. Sobald ich auf "Intelligente Aufzählungen" klicke wird mir nichts mehr angezeigt, auch nicht die anderen Tabs.

Nutze Admin 3.6.12, IoT Version 1.1.8 und Chrome Version 76.0.3809.132. Cache hab ich einmal gelöscht.

Aus dem Adapter raus gehen und erneut öffnen bringt auch nichts. Es sieht dann immer so aus wie oben.

Wenn ich eine neue Browser Instanz (inkognito) öffne, lässt sich das ganze wiederholen. Nach einmaligem Anklicken von "Intelligente Aufzählungen" passiert aber das gleiche wie oben.

In der Entwicklerkonsole steht das hier
```
185
react-dom.production.min.js:4408 TypeError: Cannot read property 'replace' of undefined
    at Function.value (Utils.js:194)
    at t.value (Enums.js:212)
    at Enums.js:230
    at Array.map (<anonymous>)
    at t.value (Enums.js:230)
    at t.value (Enums.js:311)
    at Fc (react-dom.production.min.js:3785)
    at Vc (react-dom.production.min.js:3776)
    at Bc (react-dom.production.min.js:3960)
    at Gi (react-dom.production.min.js:5514)
Utils.js:194 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at Function.value (Utils.js:194)
    at t.value (Enums.js:212)
    at Enums.js:230
    at Array.map (<anonymous>)
    at t.value (Enums.js:230)
    at t.value (Enums.js:311)
    at Fc (react-dom.production.min.js:3785)
    at Vc (react-dom.production.min.js:3776)
    at Bc (react-dom.production.min.js:3960)
    at Gi (react-dom.production.min.js:5514)
```

**Comment by Ilovegym66** [comment]
Hier jetzt in der iot-Ádapter Version 1.1.10 mit Admin-Adapter 3.7.6 und js-controller 2.2.7 auch, die Konfig Seite zeigt ein "drehendes Rad" an ( wie beim Javascript-Adapter) und dann kommt eine weiße Seite, das wars dann. ( Firefox, Linux Mint 18.3)
Mit Google-Chrome komme ich auf die Hauptseite des iot-Adapters, aber bei Smart Devices wird sie auch weiß. 

Browserkonsole Google-Chrome:
`utofocus processing was blocked because a document's URL has a fragment '#tab-instances/config/system.adapter.mihome-vacuum.2'.
jquery.fancytree-all.js:113 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
v @ jquery.fancytree-all.js:113
adminInstances.js:1065 165
32.0da5faa4.chunk.js:2 Translate: Google devices
main.0921030f.chunk.js:1 Send BROWSE!
main.0921030f.chunk.js:1 Update iot.0.smart.updates false/true
main.0921030f.chunk.js:1 BROWSE received.
2.0da5faa4.chunk.js:2 TypeError: u.forEach is not a function
so @ react-dom.production.min.js:196
react-dom.production.min.js:121 Uncaught TypeError: u.forEach is not a function
i18n.js:32 Translate: Google devices
AlexaSmartNames.js:265 Send BROWSE!
AlexaSmartNames.js:294 Update iot.0.smart.updates false/true
AlexaSmartNames.js:287 BROWSE received.
react-dom.production.min.js:196 TypeError: u.forEach is not a function
    at t.value (AlexaSmartNames.js:587)
    at t.value (AlexaSmartNames.js:770)
    at t.value (AlexaSmartNames.js:793)
    at Qi (react-dom.production.min.js:181)
    at Yi (react-dom.production.min.js:180)
    at xo (react-dom.production.min.js:261)
    at pl (react-dom.production.min.js:230)
    at vl (react-dom.production.min.js:229)
    at cl (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
so @ react-dom.production.min.js:196
react-dom.production.min.js:121 Uncaught TypeError: u.forEach is not a function
    at t.value (AlexaSmartNames.js:587)
    at t.value (AlexaSmartNames.js:770)
    at t.value (AlexaSmartNames.js:793)
    at Qi (react-dom.production.min.js:181)
    at Yi (react-dom.production.min.js:180)
    at xo (react-dom.production.min.js:261)
    at pl (react-dom.production.min.js:230)
    at vl (react-dom.production.min.js:229)
    at cl (react-dom.production.min.js:223)
    at react-dom.production.min.js:121`

**Comment by GermanBluefox** [comment]
Fixed?

**Comment by lug-gh** [comment]
Der Fehler ist heute auch bei mir aufgetreten...

**Comment by martinschm** [comment]
> Fixed?
@GermanBluefox : unfortunately not. Currently I am running

Admin 3.7.8
js-controller 2.2.8
IOT Assistants: 1.1.8

Browser is Chrome 79.0.3945.130 (Offizieller Build) (64-Bit)

**Comment by martinschm** [comment]
> Der Fehler ist heute auch bei mir aufgetreten...
> 
> Edit: Problem gefunden: eines meiner Objekte hatte bei zwei verschiedenen States den gleichen Smartname
> 
> Grund: https://forum.iobroker.net/topic/24262/licht-farbe-helligkeit-%C3%BCber-alexa-setzen
> 
> scheint nicht mehr zu funktionieren.. Ist halt blöd, dass es selbst via Webinterface funktioniert den gleichen Namen zu setzen, aber dann der ganze Adapter kaputt ist

Wie hast du denn den doppelten Namen gefunden ?

**Comment by lug-gh** [comment]
> > Der Fehler ist heute auch bei mir aufgetreten...
> > Edit: Problem gefunden: eines meiner Objekte hatte bei zwei verschiedenen States den gleichen Smartname
> > Grund: https://forum.iobroker.net/topic/24262/licht-farbe-helligkeit-%C3%BCber-alexa-setzen
> > scheint nicht mehr zu funktionieren.. Ist halt blöd, dass es selbst via Webinterface funktioniert den gleichen Namen zu setzen, aber dann der ganze Adapter kaputt ist
> 
> Wie hast du denn den doppelten Namen gefunden ?

Im RAW der jeweiligen states eines Objekts.

**Comment by martinschm** [comment]
> > > Der Fehler ist heute auch bei mir aufgetreten...
> > > Edit: Problem gefunden: eines meiner Objekte hatte bei zwei verschiedenen States den gleichen Smartname
> > > Grund: https://forum.iobroker.net/topic/24262/licht-farbe-helligkeit-%C3%BCber-alexa-setzen
> > > scheint nicht mehr zu funktionieren.. Ist halt blöd, dass es selbst via Webinterface funktioniert den gleichen Namen zu setzen, aber dann der ganze Adapter kaputt ist
> > 
> > 
> > Wie hast du denn den doppelten Namen gefunden ?
> 
> Im RAW der jeweiligen states eines Objekts.

Wenn ich jetzt noch wüßte für welche Geräte ich ein smartname angelegt habe....

**Comment by martinschm** [comment]
Hi, habe grade auf die 1.2.1 upgedatet und es geht wieder. Vermutlich durch den Fix in 1.1.9.

Vielen Dank

**Comment by mrs14** [comment]
Hallo zusammen,

ich komme nicht mehr auf die Konfiguration des iot Cloud Adapters. Gibt es da eine Lösung?

**Comment by mrs14** [comment]
![image](https://user-images.githubusercontent.com/75576590/101284613-3a498c80-37e1-11eb-80c0-4d3173f3ebc1.png)

**Comment by Apollon77** [comment]
iot.0 ist doch da?

**Comment by mrs14** [comment]
Ja, alles grün

**Comment by mrs14** [comment]
![image](https://user-images.githubusercontent.com/75576590/101284769-f86d1600-37e1-11eb-849d-9f43286a5d98.png)

**Comment by mrs14** [comment]
so sieht es aus. Das gleiche Problem habe ich auch mit dem script Adapter. Da komme ich aber manchmal noch drauf..

**Comment by mrs14** [comment]
Komme nicht in den Konfigurations tab..nur drehende Uhr..

**Comment by Apollon77** [comment]
Bitte Browser Konsole nach Fehlern prüfen und dann ein NEUES issue öffnen, in closed issues achtet niemand auf Kommentare
